=== gastonframirez/Final-DAS/Implementacion/Web/Maceo/WebContent/WEB-INF/schema/actions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="actions">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="form-beans"        minOccurs="0" maxOccurs="1" />
                <xsd:element ref="resources-bundles" minOccurs="0" maxOccurs="1" />
                <xsd:element ref="action-mappings"   minOccurs="0" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="form-beans">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="form-bean" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="form-bean">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required" />
            <xsd:attribute name="type" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="resources-bundles">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="bundle" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="bundle">
        <xsd:complexType>
            <xsd:attribute name="basename" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="action-mappings">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="action" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="action">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="parameter" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="forward"   minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="path"      type="xsd:string"  use="required" />
            <xsd:attribute name="type"      type="xsd:string"  use="required" />
            <xsd:attribute name="form"      type="xsd:string"  use="optional" />
            <xsd:attribute name="validate"  type="xsd:boolean" use="optional" />
            <xsd:attribute name="noforward" type="xsd:boolean" use="optional" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="parameter">
        <xsd:complexType>
            <xsd:attribute name="name"  type="xsd:string" use="required" />
            <xsd:attribute name="value" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="forward">
        <xsd:complexType>
            <xsd:attribute name="name"     type="xsd:string"  use="required" />
            <xsd:attribute name="path"     type="xsd:string"  use="required" />
            <xsd:attribute name="redirect" type="xsd:boolean" use="optional" />
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== gastonframirez/Final-DAS/Implementacion/Web/Maceo/WebContent/WEB-INF/actions/productos-actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:noNamespaceSchemaLocation="../schema/actions.xsd">
    <form-beans>
    </form-beans>
    <action-mappings>
        <action path="/Home.do" type="HomeAction">
            <forward name="success" path="/productos/home.jsp"/>
        </action>
        <action path="/Productos.do" type="ProductosAction">
            <forward name="success" path="/productos/categoria.jsp"/>
        </action>
        <action path="/Buscar.do" type="BuscarAction">
            <forward name="success" path="/productos/categoria.jsp"/>
        </action>
        <action path="/Redireccionar.do" type="RedirectingAction">
            <forward name="success" path="/productos/redirecting.jsp"/>
        </action>
        <action path="/Mensaje.do" type="MessageAction">
            <forward name="success" path="/productos/mensaje.jsp"/>
        </action>
        
    </action-mappings>
</actions>

=== gastonframirez/Final-DAS/Implementacion/Web/Maceo/WebContent/WEB-INF/actions/admin-actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:noNamespaceSchemaLocation="../schema/actions.xsd">
    <form-beans>
    </form-beans>
    <action-mappings>
        <action path="/Home.do" type="DashboardAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
        <action path="/Comercios.do" type="ListComerciosAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
        <action path="/AgregarComercio.do" type="ShowAddComercioAction">
            <forward name="success" path="/admin/addComercio.jsp"/>
        </action>
        <action path="/AddComercio.do" type="AddComercioAction">
            <forward name="success" path="/admin/addComercioResult.jsp"/>
        </action>
        <action path="/EditarComercio.do" type="EditComercioAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
        <action path="EstadisticasComercio.do" type="EstadisticasAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
        <action path="/Categorias.do" type="ListCategoriasAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
        <action path="/AgregarCategoria.do" type="AddCategoriaAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
        <action path="/EditarCategoria.do" type="EditCategoriaAction">
            <forward name="success" path="/admin/dashboard.jsp"/>
        </action>
    </action-mappings>
</actions>

=== gastonframirez/Final-DAS/Implementacion/Web/Maceo/WebContent/WEB-INF/actions/users-actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:noNamespaceSchemaLocation="../schema/actions.xsd">
    <form-beans>
    </form-beans>
    <action-mappings>
        <action path="/Login.do" type="LoginAction">
            <forward name="success" path="/users/login.jsp"/>
        </action>
        <action path="/Registrar.do" type="RegistrarAction">
            <forward name="success" path="/users/registrarResult.jsp"/>
        </action>
        <action path="/Registro.do" type="RegistroAction">
            <forward name="success" path="/users/registro.jsp"/>
        </action>
    </action-mappings>
</actions>
