=== gastonframirez/Final-DAS/Implementacion/Web/Maceo/WebContent/WEB-INF/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="config">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="global-forwards"  minOccurs="0" maxOccurs="1" />
                <xsd:element ref="alias-mappings"   minOccurs="0" maxOccurs="1" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="global-forwards">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="forward" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="alias-mappings">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="alias" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="alias">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="forward">
        <xsd:complexType>
            <xsd:attribute name="name"     type="xsd:string"  use="required" />
            <xsd:attribute name="path"     type="xsd:string"  use="required" />
            <xsd:attribute name="redirect" type="xsd:boolean" use="optional" />
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== gastonframirez/Final-DAS/Implementacion/Web/Maceo/WebContent/WEB-INF/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	    xsi:noNamespaceSchemaLocation="./schema/config.xsd">
    <global-forwards>
        <forward name="failure"     path="/util/failure.jsp" />
        <forward name="information" path="/util/information.jsp" />
        <forward name="success"     path="/util/success.jsp" />
        <forward name="warning"     path="/util/warning.jsp" />
    </global-forwards>
    <alias-mappings>
    
        <!-- A -->
        <alias name="admin"/>
        <!-- B -->
        <!-- C -->
        
        <!-- D -->
        <!-- E -->
        <!-- F -->
        <!-- G -->
        <!-- H -->
        <!-- I -->
        <!-- J -->
        <!-- K -->
        <!-- L -->
        <!-- M -->
        <!-- N -->
        <!-- O -->
        <!-- P -->
        <alias name="productos"/>
        <!-- Q -->
        <!-- R -->
        <!-- S -->
        <!-- T -->
        
        <!-- U -->
        <alias name="util" />
        <alias name="users"/>
        <!-- V -->
        <!-- W -->
        <!-- X -->
        <!-- Y -->
        <!-- Z -->
    </alias-mappings>
</config>
